global:
  scrape_interval: 15s # How frequently to scrape targets

scrape_configs:
  - job_name: 'toolio-services'
    metrics_path: '/metrics'
    static_configs:
      - targets:
        # Using host.docker.internal to access services running on the host machine from the container
        - 'host.docker.internal:4001' # Image Service
        - 'host.docker.internal:4002' # PDF Service
        - 'host.docker.internal:4003' # Video Service
        # Add your 4th service here if it exists, e.g.:
        # - 'host.docker.internal:4004'
